#!/usr/bin/env node
/* report-links.mjs — find prose that names another page without linking to it.
 *
 * A page that says "that is Scatter-Gather" and does not link it makes the reader search
 * for what the corpus could have handed them. This walks every hand-authored block, looks
 * for the name or alias of another page, and reports the ones the page never links.
 *
 * It REPORTS, it does not gate. Name matching is a heuristic — "Gateway", "Saga" and
 * "Repository" are ordinary English as often as they are page titles — so the output is a
 * worklist for a human, not a build failure. It is deliberately not wired into `make
 * check` for that reason.
 *
 * Four blocks are skipped because a link cannot survive there. `explain`, `production` and
 * `wild` are written by kb.mjs from plain-text arguments that it puts through esc(), so
 * markup is escaped on write and any hand-injected anchor is destroyed by the next writer
 * call; `relationships` is generated by kb.mjs link and already carries typed links. The
 * rest of a page is hand-authored HTML, and that is where a prose link belongs.
 *
 *   node scripts/report-links.mjs                  every page
 *   node scripts/report-links.mjs fan-out outbox   only these ids
 *   node scripts/report-links.mjs --json           machine-readable
 */
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { parse } from "./vendor/node-html-parser.mjs";

const ROOT = process.env.KB_ROOT
  ? resolve(process.env.KB_ROOT)
  : join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = join(ROOT, "site");

/* Blocks whose content is generated from escaped text or already typed — see header. */
const SKIP_BLOCKS = new Set(["explain", "production", "wild", "relationships"]);

/* Names that are ordinary English far more often than they are a reference to the page of
 * that name. Matching them produces noise that buries the real finds. */
const AMBIGUOUS = new Set([
  "state", "entity", "provider", "observer", "command", "builder", "adapter", "facade",
  "proxy", "bridge", "strategy", "visitor", "iterator", "mediator", "memento", "prototype",
  "registry", "repository", "gateway", "saga", "monad", "singleton", "factory", "decorator",
  "composite", "flyweight", "template-method", "interpreter", "replication", "batching",
  "sharding", "caching", "partitioning", "indexing", "pagination", "throttling",
]);

const graph = JSON.parse(readFileSync(join(SITE, "assets", "graph.json"), "utf8"));
const nodes = Object.values(graph.nodes);

/* Each page contributes its name plus any alias long enough to be unambiguous. */
const targets = [];
for (const n of nodes) {
  if (AMBIGUOUS.has(n.id)) continue;
  const phrases = [n.name, ...(n.aliases ?? [])].filter((p) => p && p.length >= 6);
  if (phrases.length) targets.push({ id: n.id, path: n.path, phrases });
}

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (e.name.endsWith(".html")) out.push(p);
  }
  return out;
}

const args = process.argv.slice(2);
const asJson = args.includes("--json");
const only = new Set(args.filter((a) => !a.startsWith("--")));

const rx = (p) => new RegExp(`\\b${p.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`, "i");

const findings = [];

for (const file of walk(SITE)) {
  const root = parse(readFileSync(file, "utf8"), { comment: true });
  const main = root.querySelector("main.doc-wrap");
  const self = main?.getAttribute("data-kb-id");
  if (!self) continue;
  if (only.size && !only.has(self)) continue;

  /* Everything this page already links, anywhere — one link per target is enough. The
   * generated "Mentioned by" list does not count: it links the pages that link HERE, so
   * reading it as this page's own links would silence the very suggestions it earns. */
  const linked = new Set();
  for (const a of root.querySelectorAll("a[href]")) {
    if (a.closest(".mentions")) continue;
    const href = a.getAttribute("href") ?? "";
    const slug = href.split("#")[0].split("/").pop()?.replace(/\.html$/, "");
    if (slug) linked.add(slug);
  }

  for (const section of main.querySelectorAll("section.doc-section")) {
    const block = section.getAttribute("data-kb-block");
    if (!block || SKIP_BLOCKS.has(block)) continue;
    /* Drop anchor text and code so an already-linked or quoted mention never matches. */
    const clone = parse(section.toString(), { comment: true });
    for (const el of clone.querySelectorAll("a, code, pre")) el.remove();
    const text = clone.textContent.replace(/\s+/g, " ");

    for (const t of targets) {
      if (t.id === self || linked.has(t.id)) continue;
      const hit = t.phrases.find((p) => rx(p).test(text));
      if (!hit) continue;
      const m = text.match(new RegExp(`[^.]*${hit.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}[^.]*\\.`, "i"));
      findings.push({
        page: self,
        file: file.slice(ROOT.length + 1),
        block,
        target: t.id,
        phrase: hit,
        sentence: (m?.[0] ?? text).trim().slice(0, 180),
      });
    }
  }
}

if (asJson) {
  console.log(JSON.stringify(findings, null, 2));
} else if (!findings.length) {
  console.log("OK — every page that names another page links it.");
} else {
  let current = "";
  for (const f of findings) {
    if (f.page !== current) { current = f.page; console.log(`\n${f.file}`); }
    console.log(`  [${f.block}] → ${f.target}  (“${f.phrase}”)`);
    console.log(`      ${f.sentence}`);
  }
  console.log(`\n${findings.length} unlinked mention(s) across ${new Set(findings.map((f) => f.page)).size} page(s).`);
  console.log("Heuristic — review each; a mention is not always worth a link.");
}
