/* builders.test.mjs — smoke tests for the builders/checkers, run with `node --test`.
 *
 * Each test copies the tiny fixture corpus (scripts/test/fixture/) to a temp dir,
 * optionally breaks it, and invokes the real script as a child process with KB_ROOT
 * pointing at the copy. A consistent builder bug would pass --check against its own
 * output; these assert against a corpus whose truth is known by construction.
 *
 * Deliberately a smoke suite, not a coverage project — the live corpus under site/
 * remains the main fixture, exercised by `make check`.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { cpSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const FIXTURE = join(HERE, "fixture");
const ALPHA = join("site", "patterns", "concurrency", "alpha.html");
const BETA = join("site", "patterns", "concurrency", "beta.html");

function withFixture(mutate) {
  const root = mkdtempSync(join(tmpdir(), "kb-fixture-"));
  cpSync(FIXTURE, root, { recursive: true });
  if (mutate) mutate(root);
  return root;
}

function run(script, root, ...args) {
  return spawnSync(process.execPath, [join(REPO, "scripts", script), ...args], {
    env: { ...process.env, KB_ROOT: root },
    encoding: "utf8",
  });
}

/* kb.mjs resolves an id to a path through graph.json, so the fixture needs building
 * before it can be read or written by id. */
function built(mutate) {
  const root = withFixture(mutate);
  const r = run("build.mjs", root);
  assert.equal(r.status, 0, r.stderr);
  return root;
}

function edit(root, rel, from, to) {
  const file = join(root, rel);
  const cur = readFileSync(file, "utf8");
  assert.ok(cur.includes(from), `fixture drifted: ${rel} no longer contains "${from}"`);
  writeFileSync(file, cur.replace(from, to));
}

test("build.mjs derives the graph, both sides of the edge present", () => {
  const root = withFixture();
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const graph = JSON.parse(readFileSync(join(root, "site", "assets", "graph.json"), "utf8"));
    assert.ok(graph.nodes.alpha && graph.nodes.beta, "both fixture nodes in the graph");
    assert.ok(graph.nodes.alpha.relations.some((x) => x.to === "beta" && x.type === "combines-with"));
    assert.ok(graph.nodes.beta.relations.some((x) => x.to === "alpha" && x.type === "combines-with"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs emits graphdata.js whose relations all target real nodes", () => {
  const root = withFixture();
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const src = readFileSync(join(root, "site", "assets", "graphdata.js"), "utf8");
    assert.match(src, /^\/\* generated by scripts\/build\.mjs/);
    const data = JSON.parse(src.slice(src.indexOf("=") + 1, src.lastIndexOf(";")));
    const ids = new Set(data.nodes.map((n) => n.id));
    for (const n of data.nodes) {
      for (const rel of n.relations) {
        assert.ok(ids.has(rel.to), `${n.id} relation points at missing node "${rel.to}"`);
      }
    }
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a one-way relationship", () => {
  const root = withFixture((r) =>
    edit(r, BETA, '<div data-kb-rel="combines-with" data-kb-to="alpha">', '<div data-kb-removed="">'));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "one-way edge must fail the build");
    assert.match(r.stderr, /one-way/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a tag outside the closed vocabulary", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, `data-kb-tags='["concurrency"]'`, `data-kb-tags='["made-up-tag"]'`));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "unknown tag must fail the build");
    assert.match(r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs passes the clean fixture, counting the mermaid click", () => {
  const root = withFixture();
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /1 mermaid click/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs fails on a dangling href", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'href="./beta.html"', 'href="./missing.html"'));
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 1, "dangling link must fail the check");
    assert.match(r.stderr, /DANGLING/);
    assert.match(r.stderr, /missing\.html/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs fails on a dangling mermaid click target", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'click B "./beta.html"', 'click B "./gone.html"'));
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 1, "dangling mermaid click must fail the check");
    assert.match(r.stderr, /gone\.html.*mermaid click/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink removes the edge from both pages, leaving the corpus buildable", () => {
  const root = built();
  try {
    const r = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /alpha: removed combines-with → beta/);
    assert.match(r.stdout, /beta: removed combines-with → alpha/);

    for (const page of [ALPHA, BETA]) {
      assert.doesNotMatch(readFileSync(join(root, page), "utf8"), /data-kb-rel/,
        `${page} still declares a relation`);
    }
    // The real proof: half an unlink is a one-way edge, which the build rejects.
    assert.equal(run("build.mjs", root).status, 0, "corpus must still build after unlink");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink fails when there is no edge to remove", () => {
  const root = built();
  try {
    assert.equal(run("kb.mjs", root, "unlink", "alpha", "beta").status, 0);
    const again = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(again.status, 1, "a second unlink has nothing to remove");
    assert.match(again.stderr, /no relation/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink takes the rel-group with the last item in it", () => {
  /* The shipped fixture has a bare rel-item; wrap it so the group branch is exercised
     without changing what every other test reads. */
  const root = built((r) => {
    edit(r, ALPHA, "  <section>\n", `  <section>
      <div class="rel-group">
        <p class="rel-type">Combines with</p>
        <div class="rel-list">
`);
    edit(r, ALPHA, "  </section>\n", `      </div>
      </div>
  </section>
`);
  });
  try {
    const r = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /with its now-empty group/);
    const html = readFileSync(join(root, ALPHA), "utf8");
    assert.doesNotMatch(html, /rel-group|rel-type|Combines with/, "the emptied group must go too");
    assert.doesNotMatch(html, /\n\n\n/, "no blank-line seam left where the group was");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a data-kb-level outside the closed vocabulary", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'data-kb-level="expert">An expert-only nuance', 'data-kb-level="wizard">An expert-only nuance'));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "unknown level must fail the build");
    assert.match(r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects an incomplete explain ladder", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA,
      '<div class="explain-item" id="explain-advanced" data-kb-level="advanced"><h3>Advanced</h3><p>Alpha with architectural teeth for seniors.</p></div>\n',
      ""));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "a two-rung ladder must fail the build");
    assert.match(r.stderr, /explain block must hold exactly one/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs get --level prunes above-level elements; the ladder stacks", () => {
  /* Accretion, both ways round: a higher lens ADDS. basic hides the expert-tagged
   * tradeoff and shows one rung; advanced reads basic+advanced stacked; expert all three. */
  const root = built();
  try {
    const basic = run("kb.mjs", root, "get", "alpha", "--level", "basic");
    assert.equal(basic.status, 0, basic.stderr);
    assert.match(basic.stdout, /universal drawback/, "untagged items stay visible");
    assert.doesNotMatch(basic.stdout, /expert-only nuance/, "expert-tagged item is pruned at basic");
    assert.match(basic.stdout, /for beginners/, "the basic explain rung shows");
    assert.doesNotMatch(basic.stdout, /architectural teeth|for staff/, "higher rungs are not there yet");

    const advanced = run("kb.mjs", root, "get", "alpha", "--level", "advanced");
    assert.equal(advanced.status, 0, advanced.stderr);
    assert.match(advanced.stdout, /for beginners[\s\S]*architectural teeth/,
      "advanced reads the basic rung and the advanced one, in that order");
    assert.doesNotMatch(advanced.stdout, /for staff/, "the expert rung waits for the expert lens");

    const expert = run("kb.mjs", root, "get", "alpha", "--level", "expert");
    assert.equal(expert.status, 0, expert.stderr);
    assert.match(expert.stdout, /for beginners[\s\S]*architectural teeth[\s\S]*for staff/,
      "expert reads all three rungs");

    const full = run("kb.mjs", root, "get", "alpha");
    assert.equal(full.status, 0, full.stderr);
    assert.match(full.stdout, /expert-only nuance/, "no --level reads the whole page");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build-pages.mjs cleans section-level stamps under the empty policy", () => {
  /* BLOCK_LEVELS is retired (empty per kind): every block shows at every lens, so a
   * hand-planted section level must be cleaned off — and authored ELEMENT levels
   * survive untouched. */
  const root = built((r) =>
    edit(r, ALPHA, 'id="description" data-kb-block="description">',
      'id="description" data-kb-block="description" data-kb-level="expert">'));
  try {
    const r = run("build-pages.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const html = readFileSync(join(root, ALPHA), "utf8");
    assert.doesNotMatch(html, /data-kb-block="[a-z]+"[^>]*data-kb-level/, "no section carries a level stamp");
    assert.match(html, /id="tradeoffs-con-1" data-kb-polarity="con" data-kb-level="expert"/,
      "authored element level is untouched");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("register variants show at exactly their lens; both-attrs and empty blocks are rejected", () => {
  /* A variant group: two adjacent registered paragraphs in description. basic sees
   * only the basic rung; expert (and the no-lens editor view keeps both). */
  const root = built((r) =>
    edit(r, ALPHA, '<section class="doc-section" id="structure" data-kb-block="structure"><h2>Structure</h2><p>',
      '<section class="doc-section" id="structure" data-kb-block="structure"><h2>Structure</h2>' +
      '<p data-kb-register="basic">Structure for newcomers.</p>' +
      '<p data-kb-register="expert">Structure at the margin.</p><p>'));
  try {
    const basic = run("kb.mjs", root, "get", "alpha", "--level", "basic");
    assert.equal(basic.status, 0, basic.stderr);
    assert.match(basic.stdout, /Structure for newcomers/, "basic rung shows at basic");
    assert.doesNotMatch(basic.stdout, /Structure at the margin/, "expert rung hidden at basic");

    const expert = run("kb.mjs", root, "get", "alpha", "--level", "expert");
    assert.match(expert.stdout, /Structure at the margin/, "expert rung shows at expert");
    assert.doesNotMatch(expert.stdout, /Structure for newcomers/, "basic rung hidden at expert");

    const editor = run("kb.mjs", root, "get", "alpha");
    assert.match(editor.stdout, /Structure for newcomers[\s\S]*Structure at the margin/,
      "no --level keeps every rung");

    /* XOR: an element with both attributes fails validate. */
    edit(root, ALPHA, '<p data-kb-register="basic">Structure for newcomers.</p>',
      '<p data-kb-register="basic" data-kb-level="basic">Structure for newcomers.</p>');
    const bad = run("kb.mjs", root, "validate", "--file", join(root, ALPHA));
    assert.equal(bad.status, 1, "level+register on one element must fail");
    assert.match(bad.stderr + bad.stdout, /both data-kb-level and data-kb-register/);
    edit(root, ALPHA, '<p data-kb-register="basic" data-kb-level="basic">Structure for newcomers.</p>',
      '<p data-kb-register="basic">Structure for newcomers.</p>');

    /* Non-empty at every lens: a block whose only content is one register rung
     * renders empty at the other two lenses. */
    edit(root, ALPHA, '<section class="doc-section" id="usage" data-kb-block="usage"><h2>When to use</h2><p>Fixture usage prose.</p></section>',
      '<section class="doc-section" id="usage" data-kb-block="usage"><h2>When to use</h2><p data-kb-register="expert">Only for experts.</p></section>');
    const empty = run("kb.mjs", root, "validate", "--file", join(root, ALPHA));
    assert.equal(empty.status, 1, "a lens-empty block must fail");
    assert.match(empty.stderr + empty.stdout, /renders empty at the basic lens/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('build-pages.mjs renders "Mentioned by" and never feeds it back into the graph', () => {
  /* A prose link only counts as a mention when no typed relation already explains it,
   * so drop the fixture edge before pointing alpha's prose at beta. The rendered list
   * is a page full of internal links: the guard that matters is that a second build
   * does not read them back as mentions of their own. */
  const root = built();
  const mentions = (r) => JSON.parse(readFileSync(join(r, "site", "assets", "graph.json"), "utf8")).nodes;
  try {
    assert.equal(run("kb.mjs", root, "unlink", "alpha", "beta").status, 0);
    edit(root, ALPHA, "<p>A minimal fixture page.",
      '<p>Prose that points at <a href="./beta.html">Beta</a>. A minimal fixture page.');
    /* Beta gets a footer nav, so the list has to land ahead of it rather than at the
     * end of <main> — the placement every real page uses. */
    edit(root, BETA, "</main>", '<nav class="docnav"><span>fixture nav</span></nav>\n</main>');
    assert.equal(run("build.mjs", root).status, 0);
    assert.equal(run("build-pages.mjs", root).status, 0);

    const beta = readFileSync(join(root, BETA), "utf8");
    assert.match(beta, /<aside class="mentions"/, "the mentioned page carries the list");
    assert.match(beta, /<a href="\.\/alpha\.html">Alpha<\/a>/, "and links back to the mentioning page");
    assert.match(beta, /<\/aside>\s*<nav class="docnav"/, "the list sits ahead of the footer nav");
    assert.doesNotMatch(readFileSync(join(root, ALPHA), "utf8"), /class="mentions"/,
      "the mentioning page gets nothing — the list is inbound only");

    /* Feedback loop: rebuild the graph from pages that now contain the rendered list. */
    assert.equal(run("build.mjs", root).status, 0);
    assert.deepEqual(mentions(root).alpha.mentions, ["beta"]);
    assert.equal(mentions(root).beta.mentions, undefined,
      "links inside the generated list are not prose mentions");
    assert.equal(run("build-pages.mjs", root, "--check").status, 0, "a second pass is a no-op");

    /* Retract the prose link: the region must go with it, byte for byte. */
    edit(root, ALPHA, 'Prose that points at <a href="./beta.html">Beta</a>. ', "");
    assert.equal(run("build.mjs", root).status, 0);
    assert.equal(run("build-pages.mjs", root).status, 0);
    assert.doesNotMatch(readFileSync(join(root, BETA), "utf8"), /mentions/,
      "a page that lost its last mention loses the region");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs refs reports each carrier separately", () => {
  const root = built();
  try {
    const r = run("kb.mjs", root, "refs", "alpha", "--json");
    assert.equal(r.status, 0, r.stderr);
    const refs = JSON.parse(r.stdout);
    assert.deepEqual(refs.relations, [{ rel: "combines-with", to: "beta" }]);
    assert.deepEqual(refs.clicks, ["beta"], "the mermaid click is a real outbound link");
    assert.deepEqual(refs.proseLinks, [], "a relation's own <a> is not a prose link");
    assert.deepEqual(refs.untyped, [], "beta is declared, so nothing is untyped");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

/* Theme membership is declared on the theme's tour step; the pattern's own "Where it
 * shows up" block restates it by hand, so the two can drift apart in either direction. */
const GAMMA = join("site", "themes", "gamma.html");

test("audit-relations.mjs passes the clean fixture's tour/fluency pair", () => {
  const root = built();
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /1 tour steps against 1 fluency items/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-relations.mjs fails when a toured pattern has no fluency item", () => {
  const root = built((r) => edit(r, ALPHA, 'data-kb-theme="gamma"', 'data-kb-theme="delta"'));
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 1, "a tour step with no matching fluency item must fail");
    assert.match(r.stderr, /TOUR WITHOUT FLUENCY/);
    assert.match(r.stderr, /alpha/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-relations.mjs fails when a fluency item names a theme that never tours it", () => {
  const root = built((r) => edit(r, GAMMA, 'data-kb-member="alpha"', 'data-kb-member="beta"'));
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 1, "a fluency item with no matching tour step must fail");
    assert.match(r.stderr, /FLUENCY WITHOUT TOUR/);
    assert.match(r.stderr, /gamma/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
