/* builders.test.mjs — smoke tests for the builders/checkers, run with `node --test`.
 *
 * Each test copies the tiny fixture corpus (scripts/test/fixture/) to a temp dir,
 * optionally breaks it, and invokes the real script as a child process with KB_ROOT
 * pointing at the copy. A consistent builder bug would pass --check against its own
 * output; these assert against a corpus whose truth is known by construction.
 *
 * Deliberately a smoke suite, not a coverage project — the live corpus under site/
 * remains the main fixture, exercised by `make check`.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { cpSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const FIXTURE = join(HERE, "fixture");
const ALPHA = join("site", "patterns", "concurrency", "alpha.html");
const BETA = join("site", "patterns", "concurrency", "beta.html");

function withFixture(mutate) {
  const root = mkdtempSync(join(tmpdir(), "kb-fixture-"));
  cpSync(FIXTURE, root, { recursive: true });
  if (mutate) mutate(root);
  return root;
}

function run(script, root, ...args) {
  return spawnSync(process.execPath, [join(REPO, "scripts", script), ...args], {
    env: { ...process.env, KB_ROOT: root },
    encoding: "utf8",
  });
}

/* kb.mjs resolves an id to a path through graph.json, so the fixture needs building
 * before it can be read or written by id. */
function built(mutate) {
  const root = withFixture(mutate);
  const r = run("build.mjs", root);
  assert.equal(r.status, 0, r.stderr);
  return root;
}

function edit(root, rel, from, to) {
  const file = join(root, rel);
  const cur = readFileSync(file, "utf8");
  assert.ok(cur.includes(from), `fixture drifted: ${rel} no longer contains "${from}"`);
  writeFileSync(file, cur.replace(from, to));
}

test("build.mjs derives the graph, both sides of the edge present", () => {
  const root = withFixture();
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const graph = JSON.parse(readFileSync(join(root, "site", "assets", "graph.json"), "utf8"));
    assert.ok(graph.nodes.alpha && graph.nodes.beta, "both fixture nodes in the graph");
    assert.ok(graph.nodes.alpha.relations.some((x) => x.to === "beta" && x.type === "combines-with"));
    assert.ok(graph.nodes.beta.relations.some((x) => x.to === "alpha" && x.type === "combines-with"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs emits graphdata.js whose relations all target real nodes", () => {
  const root = withFixture();
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const src = readFileSync(join(root, "site", "assets", "graphdata.js"), "utf8");
    assert.match(src, /^\/\* generated by scripts\/build\.mjs/);
    const data = JSON.parse(src.slice(src.indexOf("=") + 1, src.lastIndexOf(";")));
    const ids = new Set(data.nodes.map((n) => n.id));
    for (const n of data.nodes) {
      for (const rel of n.relations) {
        assert.ok(ids.has(rel.to), `${n.id} relation points at missing node "${rel.to}"`);
      }
    }
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a one-way relationship", () => {
  const root = withFixture((r) =>
    edit(r, BETA, '<div data-kb-rel="combines-with" data-kb-to="alpha">', '<div data-kb-removed="">'));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "one-way edge must fail the build");
    assert.match(r.stderr, /one-way/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a tag outside the closed vocabulary", () => {
  /* Two tags in the bad value, so this still tests MEMBERSHIP rather than tripping the
   * separate 2-5 count rule. */
  const root = withFixture((r) =>
    edit(r, ALPHA, `data-kb-tags='["concurrency","isolation"]'`, `data-kb-tags='["made-up-tag","isolation"]'`));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "unknown tag must fail the build");
    assert.match(r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs passes the clean fixture, counting the mermaid click", () => {
  const root = withFixture();
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /1 mermaid click/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs fails on a dangling href", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'href="./beta.html"', 'href="./missing.html"'));
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 1, "dangling link must fail the check");
    assert.match(r.stderr, /DANGLING/);
    assert.match(r.stderr, /missing\.html/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("check-links.mjs fails on a dangling mermaid click target", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'click B "./beta.html"', 'click B "./gone.html"'));
  try {
    const r = run("check-links.mjs", root);
    assert.equal(r.status, 1, "dangling mermaid click must fail the check");
    assert.match(r.stderr, /gone\.html.*mermaid click/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink removes the edge from both pages, leaving the corpus buildable", () => {
  const root = built();
  try {
    const r = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /alpha: removed combines-with → beta/);
    assert.match(r.stdout, /beta: removed combines-with → alpha/);

    for (const page of [ALPHA, BETA]) {
      assert.doesNotMatch(readFileSync(join(root, page), "utf8"), /data-kb-rel/,
        `${page} still declares a relation`);
    }
    // The real proof: half an unlink is a one-way edge, which the build rejects.
    assert.equal(run("build.mjs", root).status, 0, "corpus must still build after unlink");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink fails when there is no edge to remove", () => {
  const root = built();
  try {
    assert.equal(run("kb.mjs", root, "unlink", "alpha", "beta").status, 0);
    const again = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(again.status, 1, "a second unlink has nothing to remove");
    assert.match(again.stderr, /no relation/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs unlink takes the rel-group with the last item in it", () => {
  /* The shipped fixture has a bare rel-item; wrap it so the group branch is exercised
     without changing what every other test reads. */
  const root = built((r) => {
    edit(r, ALPHA, "  <section>\n", `  <section>
      <div class="rel-group">
        <p class="rel-type">Combines with</p>
        <div class="rel-list">
`);
    edit(r, ALPHA, "  </section>\n", `      </div>
      </div>
  </section>
`);
  });
  try {
    const r = run("kb.mjs", root, "unlink", "alpha", "beta");
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /with its now-empty group/);
    const html = readFileSync(join(root, ALPHA), "utf8");
    assert.doesNotMatch(html, /rel-group|rel-type|Combines with/, "the emptied group must go too");
    assert.doesNotMatch(html, /\n\n\n/, "no blank-line seam left where the group was");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects a data-kb-level outside the closed vocabulary", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA, 'data-kb-level="expert">An expert-only nuance', 'data-kb-level="wizard">An expert-only nuance'));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "unknown level must fail the build");
    assert.match(r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build.mjs rejects an incomplete explain ladder", () => {
  const root = withFixture((r) =>
    edit(r, ALPHA,
      '<div class="explain-item" id="explain-advanced" data-kb-level="advanced"><h3>Advanced</h3><p>Alpha with architectural teeth for seniors.</p></div>\n',
      ""));
  try {
    const r = run("build.mjs", root);
    assert.equal(r.status, 1, "a two-rung ladder must fail the build");
    assert.match(r.stderr, /explain block must hold exactly one/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs get --level prunes above-level elements; the ladder stacks", () => {
  /* Accretion, both ways round: a higher lens ADDS. basic hides the expert-tagged
   * tradeoff and shows one rung; advanced reads basic+advanced stacked; expert all three. */
  const root = built();
  try {
    const basic = run("kb.mjs", root, "get", "alpha", "--level", "basic");
    assert.equal(basic.status, 0, basic.stderr);
    assert.match(basic.stdout, /universal drawback/, "untagged items stay visible");
    assert.doesNotMatch(basic.stdout, /expert-only nuance/, "expert-tagged item is pruned at basic");
    assert.match(basic.stdout, /for beginners/, "the basic explain rung shows");
    assert.doesNotMatch(basic.stdout, /architectural teeth|for staff/, "higher rungs are not there yet");

    const advanced = run("kb.mjs", root, "get", "alpha", "--level", "advanced");
    assert.equal(advanced.status, 0, advanced.stderr);
    assert.match(advanced.stdout, /for beginners[\s\S]*architectural teeth/,
      "advanced reads the basic rung and the advanced one, in that order");
    assert.doesNotMatch(advanced.stdout, /for staff/, "the expert rung waits for the expert lens");

    const expert = run("kb.mjs", root, "get", "alpha", "--level", "expert");
    assert.equal(expert.status, 0, expert.stderr);
    assert.match(expert.stdout, /for beginners[\s\S]*architectural teeth[\s\S]*for staff/,
      "expert reads all three rungs");

    const full = run("kb.mjs", root, "get", "alpha");
    assert.equal(full.status, 0, full.stderr);
    assert.match(full.stdout, /expert-only nuance/, "no --level reads the whole page");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("build-pages.mjs cleans section-level stamps under the empty policy", () => {
  /* BLOCK_LEVELS is retired (empty per kind): every block shows at every lens, so a
   * hand-planted section level must be cleaned off — and authored ELEMENT levels
   * survive untouched. */
  const root = built((r) =>
    edit(r, ALPHA, 'id="description" data-kb-block="description">',
      'id="description" data-kb-block="description" data-kb-level="expert">'));
  try {
    const r = run("build-pages.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    const html = readFileSync(join(root, ALPHA), "utf8");
    assert.doesNotMatch(html, /data-kb-block="[a-z]+"[^>]*data-kb-level/, "no section carries a level stamp");
    assert.match(html, /id="tradeoffs-con-1" data-kb-polarity="con" data-kb-level="expert"/,
      "authored element level is untouched");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("register variants show at exactly their lens; both-attrs and empty blocks are rejected", () => {
  /* A variant group: two adjacent registered paragraphs in description. basic sees
   * only the basic rung; expert (and the no-lens editor view keeps both). */
  const root = built((r) =>
    edit(r, ALPHA, '<section class="doc-section" id="structure" data-kb-block="structure"><h2>Structure</h2><p>',
      '<section class="doc-section" id="structure" data-kb-block="structure"><h2>Structure</h2>' +
      '<p data-kb-register="basic">Structure for newcomers.</p>' +
      '<p data-kb-register="expert">Structure at the margin.</p><p>'));
  try {
    const basic = run("kb.mjs", root, "get", "alpha", "--level", "basic");
    assert.equal(basic.status, 0, basic.stderr);
    assert.match(basic.stdout, /Structure for newcomers/, "basic rung shows at basic");
    assert.doesNotMatch(basic.stdout, /Structure at the margin/, "expert rung hidden at basic");

    const expert = run("kb.mjs", root, "get", "alpha", "--level", "expert");
    assert.match(expert.stdout, /Structure at the margin/, "expert rung shows at expert");
    assert.doesNotMatch(expert.stdout, /Structure for newcomers/, "basic rung hidden at expert");

    const editor = run("kb.mjs", root, "get", "alpha");
    assert.match(editor.stdout, /Structure for newcomers[\s\S]*Structure at the margin/,
      "no --level keeps every rung");

    /* XOR: an element with both attributes fails validate. */
    edit(root, ALPHA, '<p data-kb-register="basic">Structure for newcomers.</p>',
      '<p data-kb-register="basic" data-kb-level="basic">Structure for newcomers.</p>');
    const bad = run("kb.mjs", root, "validate", "--file", join(root, ALPHA));
    assert.equal(bad.status, 1, "level+register on one element must fail");
    assert.match(bad.stderr + bad.stdout, /both data-kb-level and data-kb-register/);
    edit(root, ALPHA, '<p data-kb-register="basic" data-kb-level="basic">Structure for newcomers.</p>',
      '<p data-kb-register="basic">Structure for newcomers.</p>');

    /* Non-empty at every lens: a block whose only content is one register rung
     * renders empty at the other two lenses. */
    edit(root, ALPHA, '<section class="doc-section" id="usage" data-kb-block="usage"><h2>When to use</h2><p>Fixture usage prose.</p></section>',
      '<section class="doc-section" id="usage" data-kb-block="usage"><h2>When to use</h2><p data-kb-register="expert">Only for experts.</p></section>');
    const empty = run("kb.mjs", root, "validate", "--file", join(root, ALPHA));
    assert.equal(empty.status, 1, "a lens-empty block must fail");
    assert.match(empty.stderr + empty.stdout, /renders empty at the basic lens/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('build-pages.mjs renders "Mentioned by" and never feeds it back into the graph', () => {
  /* A prose link only counts as a mention when no typed relation already explains it,
   * so drop the fixture edge before pointing alpha's prose at beta. The rendered list
   * is a page full of internal links: the guard that matters is that a second build
   * does not read them back as mentions of their own. */
  const root = built();
  const mentions = (r) => JSON.parse(readFileSync(join(r, "site", "assets", "graph.json"), "utf8")).nodes;
  try {
    assert.equal(run("kb.mjs", root, "unlink", "alpha", "beta").status, 0);
    edit(root, ALPHA, "<p>A minimal fixture page.",
      '<p>Prose that points at <a href="./beta.html">Beta</a>. A minimal fixture page.');
    /* Beta gets a footer nav, so the list has to land ahead of it rather than at the
     * end of <main> — the placement every real page uses. */
    edit(root, BETA, "</main>", '<nav class="docnav"><span>fixture nav</span></nav>\n</main>');
    assert.equal(run("build.mjs", root).status, 0);
    assert.equal(run("build-pages.mjs", root).status, 0);

    const beta = readFileSync(join(root, BETA), "utf8");
    assert.match(beta, /<aside class="mentions"/, "the mentioned page carries the list");
    assert.match(beta, /<a href="\.\/alpha\.html">Alpha<\/a>/, "and links back to the mentioning page");
    assert.match(beta, /<\/aside>\s*<nav class="docnav"/, "the list sits ahead of the footer nav");
    assert.doesNotMatch(readFileSync(join(root, ALPHA), "utf8"), /class="mentions"/,
      "the mentioning page gets nothing — the list is inbound only");

    /* Feedback loop: rebuild the graph from pages that now contain the rendered list. */
    assert.equal(run("build.mjs", root).status, 0);
    assert.deepEqual(mentions(root).alpha.mentions, ["beta"]);
    assert.equal(mentions(root).beta.mentions, undefined,
      "links inside the generated list are not prose mentions");
    assert.equal(run("build-pages.mjs", root, "--check").status, 0, "a second pass is a no-op");

    /* Retract the prose link: the region must go with it, byte for byte. */
    edit(root, ALPHA, 'Prose that points at <a href="./beta.html">Beta</a>. ', "");
    assert.equal(run("build.mjs", root).status, 0);
    assert.equal(run("build-pages.mjs", root).status, 0);
    assert.doesNotMatch(readFileSync(join(root, BETA), "utf8"), /mentions/,
      "a page that lost its last mention loses the region");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs refs reports each carrier separately", () => {
  const root = built();
  try {
    const r = run("kb.mjs", root, "refs", "alpha", "--json");
    assert.equal(r.status, 0, r.stderr);
    const refs = JSON.parse(r.stdout);
    assert.deepEqual(refs.relations, [{ rel: "combines-with", to: "beta" }]);
    assert.deepEqual(refs.clicks, ["beta"], "the mermaid click is a real outbound link");
    assert.deepEqual(refs.proseLinks, [], "a relation's own <a> is not a prose link");
    assert.deepEqual(refs.untyped, [], "beta is declared, so nothing is untyped");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

/* Theme membership is declared on the theme's tour step; the pattern's own "Where it
 * shows up" block restates it by hand, so the two can drift apart in either direction. */
const GAMMA = join("site", "themes", "gamma.html");

test("audit-relations.mjs passes the clean fixture's tour/fluency pair", () => {
  const root = built();
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /1 tour steps against 1 fluency items/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-relations.mjs fails when a toured pattern has no fluency item", () => {
  const root = built((r) => edit(r, ALPHA, 'data-kb-theme="gamma"', 'data-kb-theme="delta"'));
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 1, "a tour step with no matching fluency item must fail");
    assert.match(r.stderr, /TOUR WITHOUT FLUENCY/);
    assert.match(r.stderr, /alpha/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-relations.mjs fails when a fluency item names a theme that never tours it", () => {
  const root = built((r) => edit(r, GAMMA, 'data-kb-member="alpha"', 'data-kb-member="beta"'));
  try {
    const r = run("audit-relations.mjs", root);
    assert.equal(r.status, 1, "a fluency item with no matching tour step must fail");
    assert.match(r.stderr, /FLUENCY WITHOUT TOUR/);
    assert.match(r.stderr, /gamma/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

/* --- the wild/production round trip ---------------------------------------
 * Both writers replace the whole block, so fixing one entry means re-supplying its
 * neighbours. `get --json` dumps them in the writers' own shape to make that a round
 * trip rather than a re-type — and the round trip has to be lossless, because the
 * rendered prose these were otherwise re-typed from carries neither the data-kb-level
 * tags (1,900+ of them across the live corpus) nor the inline <code>. */

/* The writers take an id; the dump comes back off the built page. */
function dumpItems(root, id) {
  const r = run("kb.mjs", root, "get", id, "--json");
  assert.equal(r.status, 0, r.stderr);
  return JSON.parse(r.stdout).items ?? {};
}

test("kb.mjs wild round-trips level tags and inline <code>, and escapes everything else", () => {
  const root = built();
  try {
    const written = [
      { id: "plain", name: "Plain", note: "No tag, no markup." },
      { id: "tagged", name: "Go <code>x/time/rate</code>", note: "Its <code>rate.Limiter</code> is a token bucket.", level: "advanced" },
      { id: "risky", name: "Risky", note: 'Not a link: <a href="x">x</a> & <b>bold</b>.', level: "expert" },
    ];
    assert.equal(run("kb.mjs", root, "wild", "alpha", "--items", JSON.stringify(written)).status, 0);
    assert.equal(run("build.mjs", root).status, 0);

    const page = readFileSync(join(root, ALPHA), "utf8");
    assert.match(page, /<code>rate\.Limiter<\/code>/, "<code> is the one tag that survives");
    assert.doesNotMatch(page, /<a href="x">/, "a hand-passed link is escaped, not rendered");
    assert.match(page, /&lt;a href="x"&gt;/, "…and lands as visible text instead");
    assert.match(page, /data-kb-example="tagged" data-kb-level="advanced"/, "the lens tag is written");

    /* The property that matters: dump it, hand it straight back, nothing moves. The dump
     * reports what is ON the page, so the escaped item comes back escaped — and feeding
     * that in again is still a no-op, since an existing entity is never re-escaped. */
    const first = dumpItems(root, "alpha").wild;
    assert.deepEqual(first.slice(0, 2), written.slice(0, 2), "clean items dump exactly as written");
    assert.equal(first[2].note, 'Not a link: &lt;a href="x"&gt;x&lt;/a&gt; &amp; &lt;b&gt;bold&lt;/b&gt;.',
      "the escaped item dumps in its authored form");
    assert.equal(run("kb.mjs", root, "wild", "alpha", "--items", JSON.stringify(first)).status, 0);
    assert.equal(run("build.mjs", root).status, 0);
    assert.deepEqual(dumpItems(root, "alpha").wild, first, "re-supplying the dump is a fixed point");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs production round-trips level tags; a checklist gate takes both forms", () => {
  const root = built();
  try {
    const knobs = [
      { label: "Pool size", note: "How many connections the pool holds." },
      { label: "Timeout", note: "Bound on <code>read_timeout</code>.", level: "advanced" },
    ];
    const signals = [{ label: "Queue depth", note: "Items waiting." }];
    const failures = [{ label: "Saturation", note: "Everything queues.", level: "expert" }];
    /* A bare string is the everyday form; the object form carries a lens tag back. */
    const checklist = ["Set an explicit timeout.", { text: "Load-test the pool.", level: "advanced" }];
    assert.equal(run("kb.mjs", root, "production", "alpha",
      "--knobs", JSON.stringify(knobs), "--signals", JSON.stringify(signals),
      "--failures", JSON.stringify(failures), "--checklist", JSON.stringify(checklist)).status, 0);
    assert.equal(run("build.mjs", root).status, 0);

    const dumped = dumpItems(root, "alpha").production;
    assert.deepEqual(dumped.knobs, knobs);
    assert.deepEqual(dumped.signals, signals);
    assert.deepEqual(dumped.failures, failures);
    assert.deepEqual(dumped.checklist, [{ text: "Set an explicit timeout." }, { text: "Load-test the pool.", level: "advanced" }],
      "a bare string dumps as an object; the tagged one keeps its level");

    assert.equal(run("kb.mjs", root, "production", "alpha",
      "--knobs", JSON.stringify(dumped.knobs), "--signals", JSON.stringify(dumped.signals),
      "--failures", JSON.stringify(dumped.failures), "--checklist", JSON.stringify(dumped.checklist)).status, 0);
    assert.equal(run("build.mjs", root).status, 0);
    assert.deepEqual(dumpItems(root, "alpha").production, dumped, "re-supplying the dump is a fixed point");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs rejects an item level outside the closed vocabulary", () => {
  const root = built();
  try {
    const r = run("kb.mjs", root, "wild", "alpha", "--items",
      JSON.stringify([{ id: "x", name: "X", note: "n", level: "senior" }]));
    assert.equal(r.status, 1, "an invented level must not reach the page");
    assert.match(r.stderr, /level must be one of/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("kb.mjs get --level never truncates the item dump", () => {
  /* The trap this exists to close: a --level basic dump handed back to the writer
   * would delete every item above that lens. Items read off the unpruned page. */
  const root = built();
  try {
    const written = [
      { id: "plain", name: "Plain", note: "Untagged." },
      { id: "deep", name: "Deep", note: "Expert only.", level: "expert" },
    ];
    assert.equal(run("kb.mjs", root, "wild", "alpha", "--items", JSON.stringify(written)).status, 0);
    assert.equal(run("build.mjs", root).status, 0);

    const scoped = run("kb.mjs", root, "get", "alpha", "--block", "wild", "--level", "basic", "--json");
    assert.equal(scoped.status, 0, scoped.stderr);
    const parsed = JSON.parse(scoped.stdout);
    assert.doesNotMatch(parsed.blocks.wild, /Expert only/, "the prose IS scoped to the lens");
    assert.deepEqual(parsed.items.wild, written, "…but the items are not, or a round trip would delete one");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

/* ---------------- audit-vocab.mjs ----------------
 * The vocabularies and the page documenting them, held to each other. T2 (every tag used
 * on 3+ pages) and S1 (no dead curated synonym) are corpus-scale and skipped under
 * KB_ROOT, so they are exercised by `make check` against site/, not here. */

/* audit-vocab reads a built graph AND the generated vocab.html, so the fixture needs
 * both. build-pages.mjs supplies the JSON-LD that V3 inspects. */
function vocabReady(mutate) {
  const root = built(mutate);
  assert.equal(run("build-pages.mjs", root).status, 0);
  assert.equal(run("build-vocab.mjs", root).status, 0);
  return root;
}

test("audit-vocab.mjs passes the clean fixture", () => {
  const root = vocabReady();
  try {
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /Every term the pages use is defined/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-vocab.mjs fails on a data-kb-* the ontology never documents", () => {
  const root = vocabReady((r) => edit(r, ALPHA, "data-kb-kind=", 'data-kb-bogus="x" data-kb-kind='));
  try {
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 1, "an undocumented attribute must fail");
    assert.match(r.stderr, /V1 UNDOCUMENTED: data-kb-bogus/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-vocab.mjs fails when a relation verb has no fragment on vocab.html", () => {
  const root = vocabReady();
  try {
    edit(root, join("site", "vocab.html"), 'id="combines-with"', 'id="combines-elsewhere"');
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 1, "a verb with no definition must fail");
    assert.match(r.stderr, /V2 NO FRAGMENT: relation verb "combines-with"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

/* The other half of the polarity rule — that build-pages' ITEMS table and POLARITIES name
 * the same eight values — is asserted inside build-pages.mjs itself rather than here. Only
 * the corpus is redirectable by KB_ROOT, so a test cannot hand the builder a divergent
 * model.mjs to fail against; every `make all` and every builder test above runs the guard. */

test("audit-vocab.mjs fails when a page's JSON-LD emits an undefined kb: term", () => {
  const root = vocabReady();
  try {
    edit(root, ALPHA, '"kb:kind"', '"kb:notaterm"');
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 1, "an undefined emitted term must fail");
    assert.match(r.stderr, /V3 UNDEFINED TERM/);
    assert.match(r.stderr, /kb:notaterm/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-vocab.mjs fails when a namespaced vocabulary loses its fragment", () => {
  /* The verb check above covers the four families whose ids are bare. Everything added
   * since — kinds, blocks, polarities, bands, groups, tags, languages — is checked through
   * one prefixed loop, so one case proves the shape. Tags are the interesting member: they
   * had no anchors at all until the page was rebuilt around a single row component. */
  const root = vocabReady();
  try {
    edit(root, join("site", "vocab.html"), 'id="tag-caching"', 'id="tag-elsewhere"');
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 1, "a tag with no definition must fail");
    assert.match(r.stderr, /V2 NO FRAGMENT: tag "caching"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-vocab.mjs fails on a sketch language the closed set never named", () => {
  /* The corpus-scale half of the membership rule validate.mjs enforces per page. Written
   * against data-kb-lang rather than data-kb-polarity because polarity sits in a generated
   * region — build-pages.mjs re-derives it, so a mutation made before the build is simply
   * overwritten and proves nothing. The lang is authored and survives. Edited AFTER the
   * build for the same reason: this gate exists for a page edited by hand and not yet
   * rebuilt. Both values run through one loop, so this covers the shape. */
  const root = vocabReady();
  try {
    edit(root, ALPHA, 'data-kb-lang="typescript"', 'data-kb-lang="cobol"');
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 1, "an unknown sketch language must fail the corpus gate");
    assert.match(r.stderr, /V4 UNKNOWN VALUE/);
    assert.match(r.stderr, /data-kb-lang="cobol"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("validate.mjs rejects a polarity outside the closed vocabulary", () => {
  /* The same rule one layer earlier. audit-vocab is the corpus sweep; this is the check the
   * authoring hook runs, so a writer hears about it while they still have the page open. */
  const root = built();
  try {
    edit(root, ALPHA, 'data-kb-polarity="con"', 'data-kb-polarity="neutral"');
    const r = run("kb.mjs", root, "validate", "alpha");
    assert.equal(r.status, 1, "an invented polarity must not validate");
    assert.match(r.stdout + r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("validate.mjs rejects a sketch language the highlighter does not know", () => {
  /* data-kb-lang lives on a <code> inside a <pre>, which the parser hands back as raw text
   * — so this is read off the raw source, and a DOM query would silently never fire. */
  const root = built();
  try {
    edit(root, ALPHA, 'data-kb-lang="typescript"', 'data-kb-lang="cobol"');
    const r = run("kb.mjs", root, "validate", "alpha");
    assert.equal(r.status, 1, "an unknown sketch language must not validate");
    assert.match(r.stdout + r.stderr, /closed vocabulary/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("audit-vocab.mjs warns when a tag maps 1:1 onto a kind", () => {
  /* gamma is the fixture's only theme; give it a tag no pattern carries and that tag
   * covers 100% of one kind, which is what a kind marker is. It warns, never fails —
   * retiring such a tag means retagging every page that carries it. */
  const root = vocabReady((r) =>
    edit(r, GAMMA, `data-kb-tags='["concurrency","isolation"]'`, `data-kb-tags='["caching","isolation"]'`));
  try {
    const r = run("audit-vocab.mjs", root);
    assert.equal(r.status, 0, "a kind marker warns rather than failing");
    assert.match(r.stdout, /T3 KIND MARKER: "caching"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("validate.mjs holds a page to 2-5 tags", () => {
  for (const [tags, why] of [
    [`["concurrency"]`, "one tag groups nothing"],
    [`["concurrency","isolation","caching","latency","routing","security"]`, "six tags filter nothing"],
  ]) {
    const root = built((r) => edit(r, ALPHA, `data-kb-tags='["concurrency","isolation"]'`, `data-kb-tags='${tags}'`));
    try {
      const r = run("kb.mjs", root, "validate", "alpha");
      assert.equal(r.status, 1, why);
      assert.match(r.stdout + r.stderr, /2-5/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }
});
